### ISSUE TITLE
Viewing account page of another user should show only their workspaces/repos

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#461]
Currently if you look at another user's account page, e.g. https://www.v2.opensourcebrain.org/user/865fecc7-7c23-49ab-a47d-2ac4c0c8d5c2, it shows the workspaces YOU have access to, and ALL of the repositories.

Related to https://github.com/OpenSourceBrain/OSBv2/issues/447, but a bigger issue to fix.

**Comment by filippomc** [comment]
The issue is really the same from #447, as I can reproduce the issue with an admin user. For non-admin users, the workspaces list is the list of all public repositories owned by that user (private repos are not shown in the list).

The repositories issue has been fixed in the latest development (deployed on v2dev).

**Comment by pgleeson** [comment]
Not really the same... If there are 2 non-admin users A and B, and A looks at the user page of B, then it's reasonable that the workspaces and repos listed are the ones belonging to B. This is broken on v2dev, user B's page shows user A's ws/repos

**Comment by filippomc** [comment]
This is b looking at [a's page](https://v2dev.opensourcebrain.org/user/9e347304-2ba4-4afd-8857-c75498371294) (yes my test users are a and b :) ) and no workspace is shown.
![image](https://user-images.githubusercontent.com/46561561/164712282-4c2a936d-795a-446f-93e1-b26386c9369a.png)

I can see two errors:
- should see 3 workspaces and 0 are shown. This is because it's not showing the a's public workspaces, which are the only ones that b would be allowed to see
- The link in the menu doesn't change to a's page when I click on it

**Comment by sanjayankur31** [comment]
I thought we'd fixed this one, but I see that on v2dev I'm still not able to see public workspaces of other users. Looking into it again now.

**Comment by filippomc** [comment]
adding publicable=true to the query should fix
